runtime: nodejs
env: flex

network:
  session_affinity: true

manual_scaling:
  instances: 1

env_variables:
  GOOGLE_API_KEY: ""
  DEMO_AGENT_MODEL: "gemini-2.5-flash-native-audio-preview-12-2025"

runtime_config:
      operating_system: "ubuntu24"
      runtime_version: "24"
